---
abstract: 'Mason wrapper for Dancer'
author:
  - 'Yanick Champoux'
build_requires:
  Dancer::FileUtils: 0
  Dancer::Test: 0
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Plack::Handler::FCGI: 0
  Plack::Runner: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Template-Mason
provides:
  Dancer::Template::Mason:
    file: lib/Dancer/Template/Mason.pm
    version: 0.004000
requires:
  Dancer: 0
  FindBin: 0
  HTML::Mason::Interp: 0
  Moo: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dancer-Template-Mason
  homepage: http://search.cpan.org/dist/Dancer-Template-Mason/
  repository: https://github.com/yanick/Dancer-Template-Mason.git
version: 0.004000
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
