---
abstract: 'Mason wrapper for Dancer'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Dancer::FileUtils: '0'
  Dancer::Test: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Plack::Handler::FCGI: '0'
  Plack::Runner: '0'
  Test::More: '0.88'
  lib: '0'
  perl: '5.006'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Template-Mason
no_index:
  directory:
    - inc
provides:
  Dancer::Template::Mason:
    file: lib/Dancer/Template/Mason.pm
    version: '0.004001'
requires:
  Dancer: '0'
  FindBin: '0'
  HTML::Mason::Interp: '0'
  Moo: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Dancer-Template-Mason/issues
  homepage: http://search.cpan.org/dist/Dancer-Template-Mason/
  repository: https://github.com/yanick/Dancer-Template-Mason.git
version: '0.004001'
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Danijel Tasov <dt@korn.shell.la>'
  - 'Steve Simms <steve@deefs.net>'
  - 'boris shomodjvarac <shomodj@oginwm09.(none)>'
  - 'franck cuny <franck@lumberjaph.net>'
